# Generated by Django 4.0.2 on 2022-03-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
